# Generated by Django 4.2.20 on 2025-03-15 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("writing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlyphPracticeProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("successful_attempts", models.PositiveIntegerField(default=0)),
                ("last_practiced", models.DateTimeField(auto_now=True)),
                ("mastered", models.BooleanField(default=False)),
                (
                    "glyph",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="writing.glyph"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Glyph practice progress",
                "unique_together": {("user", "glyph")},
            },
        ),
    ]
