# Generated by Django 4.2.20 on 2025-03-27 08:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("writing", "0002_glyphpracticeprogress"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="glyph",
            options={"ordering": ["name"]},
        ),
    ]
