# Generated by Django 4.2.20 on 2025-03-30 05:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tutor", "0002_message"),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("youtube_id", models.CharField(max_length=20, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("channel", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("duration", models.CharField(max_length=20)),
                ("thumbnail_url", models.URLField()),
                ("published_at", models.DateTimeField()),
                ("view_count", models.IntegerField(default=0)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="beginner",
                        max_length=20,
                    ),
                ),
                ("topics", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
