# Generated by Django 4.2.20 on 2025-03-30 18:05

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tutor", "0003_videoresource"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transcript",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("language", models.CharField(default="en", max_length=10)),
                ("is_generated", models.BooleanField(default=False)),
                ("has_embeddings", models.BooleanField(default=False)),
                (
                    "embeddings",
                    pgvector.django.vector.VectorField(dimensions=1536, null=True),
                ),
                ("segments", models.JSONField(default=list)),
                ("vocabulary", models.JSONField(default=list)),
                (
                    "video",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transcript",
                        to="tutor.videoresource",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["video"], name="tutor_trans_video_i_2b9d98_idx"
                    ),
                    pgvector.django.indexes.HnswIndex(
                        ef_construction=64,
                        fields=["embeddings"],
                        m=16,
                        name="transcript_embeddings_hnsw_idx",
                        opclasses=["vector_cosine_ops"],
                    ),
                ],
            },
        ),
    ]
