# Generated by Django 4.2.20 on 2025-03-30 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tutor", "0004_transcript"),
    ]

    operations = [
        migrations.CreateModel(
            name="LearningProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("videos_watched", models.PositiveIntegerField(default=0)),
                ("quizzes_completed", models.PositiveIntegerField(default=0)),
                ("conversations_count", models.PositiveIntegerField(default=0)),
                ("known_vocabulary", models.JSONField(default=list)),
                ("vocabulary_strength", models.JSONField(default=dict)),
                ("listening_level", models.FloatField(default=0.0)),
                ("translation_level", models.FloatField(default=0.0)),
                ("grammar_level", models.FloatField(default=0.0)),
                ("interests", models.JSONField(default=list)),
                (
                    "learning_style",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("last_activity", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
