# Generated by Django 4.2.20 on 2025-03-31 01:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tutor", "0005_learningprogress"),
    ]

    operations = [
        migrations.CreateModel(
            name="TokiPonaPhrase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(default="Toki Pona Exercise", max_length=100),
                ),
                ("text", models.CharField(max_length=200)),
                ("translations", models.JSONField()),
                (
                    "audio_file",
                    models.FileField(blank=True, null=True, upload_to="audio/"),
                ),
                (
                    "youtube_video_id",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("transcript", models.TextField(blank=True)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="beginner",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="QuizAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "questions",
                    models.JSONField(
                        help_text="JSON array of quiz questions with options and correct answers"
                    ),
                ),
                (
                    "user_answers",
                    models.JSONField(
                        help_text="JSON array of user-selected answer indices"
                    ),
                ),
                (
                    "correct_answers",
                    models.JSONField(
                        help_text="JSON array of boolean values indicating correct/incorrect"
                    ),
                ),
                ("score", models.FloatField(help_text="Percentage score (0-100)")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "feedback",
                    models.TextField(
                        blank=True, help_text="Textual feedback provided to the user"
                    ),
                ),
                (
                    "areas_for_improvement",
                    models.JSONField(
                        default=list,
                        help_text="List of areas to focus on for improvement",
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="beginner",
                        help_text="Difficulty level of the quiz",
                        max_length=20,
                    ),
                ),
                (
                    "question_count",
                    models.PositiveIntegerField(
                        default=5, help_text="Number of questions in the quiz"
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_attempts",
                        to="tutor.conversation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quiz_attempts",
                        to="tutor.videoresource",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quiz Attempt",
                "verbose_name_plural": "Quiz Attempts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ListeningExerciseProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completed", models.BooleanField(default=False)),
                ("last_attempt", models.DateTimeField(auto_now=True)),
                ("correct_attempts", models.PositiveIntegerField(default=0)),
                ("total_attempts", models.PositiveIntegerField(default=0)),
                (
                    "phrase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tutor.tokiponaphrase",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Listening exercise progress",
            },
        ),
        migrations.AddConstraint(
            model_name="listeningexerciseprogress",
            constraint=models.UniqueConstraint(
                fields=("user", "phrase"), name="unique_user_phrase"
            ),
        ),
    ]
