# Generated by Django 4.2.20 on 2025-03-30 11:57

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):
    operations = [
        VectorExtension(),
    ]
