# Generated by Django 4.2.20 on 2025-03-15 23:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SignReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("meaning", models.CharField(max_length=100)),
                ("video", models.FileField(blank=True, null=True, upload_to="signs/")),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="signs/thumbnails/"
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("example_sentence", models.CharField(blank=True, max_length=200)),
                ("landmarks", models.JSONField(blank=True, null=True)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="beginner",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
