# Generated by Django 4.2.20 on 2025-03-08 17:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SignReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("video", models.FileField(blank=True, null=True, upload_to="signs/")),
                ("landmarks", models.JSONField(null=True)),
            ],
        ),
    ]
