# Generated by Django 4.2.20 on 2025-03-15 23:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("signing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SigningProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("successful_attempts", models.PositiveIntegerField(default=0)),
                ("last_practiced", models.DateTimeField(auto_now=True)),
                ("mastered", models.BooleanField(default=False)),
                (
                    "sign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="signing.signreference",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Signing progress",
                "unique_together": {("user", "sign")},
            },
        ),
    ]
