# Generated by Django 4.2.20 on 2025-03-15 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("listening", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ListeningExerciseProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completed", models.BooleanField(default=False)),
                ("last_attempt", models.DateTimeField(auto_now=True)),
                ("correct_attempts", models.PositiveIntegerField(default=0)),
                ("total_attempts", models.PositiveIntegerField(default=0)),
                (
                    "phrase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="listening.tokiponaphrase",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Listening exercise progress",
                "unique_together": {("user", "phrase")},
            },
        ),
    ]
