# Generated by Django 4.2.20 on 2025-03-31 01:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("listening", "0002_listeningexerciseprogress"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ListeningExerciseProgress",
        ),
        migrations.DeleteModel(
            name="TokiPonaPhrase",
        ),
    ]
